### ISSUE TITLE
Fatal error when displaying Products

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/gvg_bulk_update#11]
<b>Warning</b>:  Undefined array key 6818 in <b>C:\apache\htdocs\wordpress\wp-content\plugins\gvg_bulk_update\admin\class-gvg-bulk-update-page.php</b> on line <b>296</b><br />
<br />
<b>Fatal error</b>:  Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, null given in C:\apache\htdocs\wordpress\wp-content\plugins\gvg_bulk_update\admin\class-gvg-bulk-update-page.php:296
```
Stack trace:
#0 C:\apache\htdocs\wordpress\wp-content\plugins\oik-bwtrace\libs\class-BW-.php(97): gvg_bulk_update_page-&gt;gvg_display_products()
#1 C:\apache\htdocs\wordpress\wp-content\plugins\gvg_bulk_update\admin\gvg_bulk_update.php(18): BW_::oik_box(NULL, 'gvg_display_pro...', 'Products', Array)
#2 C:\apache\htdocs\gardenvista\wp-includes\class-wp-hook.php(307): gvg_bulk_update_do_page('')
#3 C:\apache\htdocs\gardenvista\wp-includes\class-wp-hook.php(331): WP_Hook-&gt;apply_filters('', Array)
#4 C:\apache\htdocs\gardenvista\wp-includes\plugin.php(474): WP_Hook-&gt;do_action(Array)
#5 C:\apache\htdocs\gardenvista\wp-admin\admin.php(259): do_action('tools_page_gvg_...')
#6 C:\apache\htdocs\gardenvista\wp-admin\tools.php(40): require_once('C:\\apache\\htdoc...')
#7 {main}
  thrown in <b>C:\apache\htdocs\wordpress\wp-content\plugins\gvg_bulk_update\admin\class-gvg-bulk-update-page.php</b> on line <b>296</b><br />
```

**Comment by bobbingwide** [comment]
This problem still happens with PHP 8.x

Warning: Undefined array key 9566 in C:\apache\htdocs\wordpress\wp-content\plugins\gvg_bulk_update\libs\class-gvg-bulk-update-page.php on line 296

followed by

Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in C:\apache\htdocs\wordpress\wp-content\plugins\gvg_bulk_update\libs\class-gvg-bulk-update-page.php:296 

```
Stack trace: #0 C:\apache\htdocs\wordpress\wp-content\plugins\oik-bwtrace\libs\class-BW-.php(97): gvg_bulk_update_page->gvg_display_products() #1 C:\apache\htdocs\wordpress\wp-content\plugins\gvg_bulk_update\libs\class-gvg-admin.php(52): BW_::oik_box(NULL, 'gvg_display_pro...', 'Products', Array) #2 C:\apache\htdocs\gardenvista\wp-includes\class-wp-hook.php(324): GVG_Admin->nav_tab_optional_upgrades('') #3 C:\apache\htdocs\gardenvista\wp-includes\class-wp-hook.php(348): WP_Hook->apply_filters('', Array) #4 C:\apache\htdocs\gardenvista\wp-includes\plugin.php(517): WP_Hook->do_action(Array) #5 C:\apache\htdocs\wordpress\wp-content\plugins\gvg_bulk_update\libs\class-gvg-admin.php(21): do_action('gvg_nav_tab_opt...') #6 C:\apache\htdocs\wordpress\wp-content\plugins\gvg_bulk_update\admin\gvg_bulk_update.php(19): GVG_Admin->process() #7 C:\apache\htdocs\gardenvista\wp-includes\class-wp-hook.php(324): gvg_admin_page('') #8 C:\apache\htdocs\gardenvista\wp-includes\class-wp-hook.php(348): WP_Hook->apply_filters('', Array) #9 C:\apache\htdocs\gardenvista\wp-includes\plugin.php(517): WP_Hook->do_action(Array) #10 C:\apache\htdocs\gardenvista\wp-admin\admin.php(259): do_action('tools_page_gvg_...') #11 C:\apache\htdocs\gardenvista\wp-admin\tools.php(40): require_once('C:\\apache\\htdoc...') #12 {main} thrown in C:\apache\htdocs\wordpress\wp-content\plugins\gvg_bulk_update\libs\class-gvg-bulk-update-page.php on line 296
```

**Comment by bobbingwide** [comment]
I've fixed this by add some logic to check that all the posts are listed in the available_options_map.
When a new product has been added a message is displayed in the Form below the buttons saying
"Reload option list cache for new products:"
then it lists the new products as post ID and post title.

In the code that failed, the Products box will display "Please reload option list cache" for each product that's not found in the available_options_map.

**Comment by bobbingwide** [comment]
Delivered in v1.3.2
